ifdef MAKE_INCLUDES
include $(MAKE_INCLUDES)
endif

iscsi-scst-y += config.o
iscsi-scst-y += conn.o
iscsi-scst-y += digest.o
iscsi-scst-y += event.o
iscsi-scst-y += iscsi.o
iscsi-scst-y += iscsit_transport.o
iscsi-scst-y += nthread.o
iscsi-scst-y += param.o
iscsi-scst-y += session.o
iscsi-scst-y += target.o

ifndef SCST_USERMODE
obj-$(CONFIG_SCST_ISCSI) += iscsi-scst.o isert-scst/
else
iscsi-scst-y += scst_compat.o
obj-$(CONFIG_SCST_ISCSI) += iscsi-scst.o
endif
